### ISSUE TITLE
begin to transform train split 

### ISSUE THREAD

**Issue by yijiuzai** [MUGE-2021/image-retrieval-baseline#10]
9504it [00:30, 302.00it/s]Killed

**Comment by yijiuzai** [comment]
9504it [00:30, 302.00it/s]Killed

**Comment by yangapku** [comment]
您好，这一步操作确实需要暂时把数据存放在内存。如果内存无法满足要求，可以考虑修改为LMDB等文件索引存储格式。

**Comment by ronghonghui** [comment]
请问您这边有实现好的代码吗

**Comment by ronghonghui** [comment]
请问有实现好的代码可以参考一下吗

**Comment by yangapku** [comment]
https://github.com/billjie1/Chinese-CLIP

**Comment by ronghonghui** [comment]
感谢北大爷！
