### ISSUE TITLE
内存需求

### ISSUE THREAD

**Issue by zhouwei5113** [MUGE-2021/image-retrieval-baseline#4]
训练代码来看需要将数据全部load进内容，请问对内存的要求多大？

**Comment by yangapku** [comment]
您好，使用单机8卡执行readme默认的训练命令，当训练启动时占用了约50GB内存

**Comment by zhouwei5113** [comment]
> 您好，使用单机8卡执行readme默认的训练命令，当训练启动时占用了约50GB内存

奇怪，我这边200G内存的机器都OOM了

**Comment by yangapku** [comment]
@zhouwei5113 您好，看到您自己关闭了issue，请问是问题已经解决了吗？

**Comment by remember00000** [comment]
@yangapku @zhouwei5113  您好, 我使用的pycharm远程使用服务器运行, 使用的内存是这些, 看起来是200G, 但是也有同样的问题, 请问是哪里有问题呢
![image](https://user-images.githubusercontent.com/67587712/189264501-f927589c-cfed-4b92-8ec6-6d0ddf3e690d.png)
