### ISSUE TITLE
val_loss 增大的问题

### ISSUE THREAD

**Issue by zhangqianYY** [MUGE-2021/image-retrieval-baseline#5]
你好，我使用默认指令训练，随着epoch增加，训练样本loss在减少，模型测试在验证集上的准确率也在增加，但疑惑为什么val_loss却一直在升高？

**Comment by zhangqianYY** [comment]
val_loss: https://drive.google.com/file/d/17b-W3ke0tCvUQXK7tY5Z6LrSGAMxXIhC/view?usp=sharing

**Comment by zhangqianYY** [comment]
val_loss: https://drive.google.com/file/d/17b-W3ke0tCvUQXK7tY5Z6LrSGAMxXIhC/view?usp=sharing  ,横坐标是epoch数

**Comment by zhangqianYY** [comment]
![val_loss](https://user-images.githubusercontent.com/22525110/159421617-630391b0-6e35-4ce0-8d45-c8552fe1a310.png)

横坐标是epoch数

**Comment by yangapku** [comment]
您好，这个情况是正常的，我们建议以验证集上的准确率作为评价模型训练情况的标准。根据代码中cross-entropy的计算方式（可以参见CLIP论文figure 3 https://arxiv.org/pdf/2103.00020.pdf），验证集loss的绝对值大小，会和模型当前训练的temperature值(模型中具体为1/exp(logit_scale)) 有关。在我们的训练中，temperature随着模型训练一起调节，会倾向于不断变大（logit_scale逐渐减小），因此会造成一个验证集loss上升的趋势。但是实际上，模型对于验证集商品图的区分能力在不断提升，体现在在验证集上的准确率逐渐增加。

**Comment by zhangqianYY** [comment]
1. 感谢您的回复，logit_scale确实是在逐渐减小，相应的temperature=1/exp(logit_scale) 在增大，但该代码https://github.com/MUGE-2021/image-retrieval-baseline/blob/ef154cc829b6411762bcdff7933622351976f1c4/src/training/train.py#L47 中用的是logit_scale与相似度相乘，我理解并代码中没有用到temperature这个参数？

**Comment by yangapku** [comment]
恩恩，代码中实际用到的只有logit_scale，temperature只是算法概念上的，实际随模型一起训练的是logit_scale

**Comment by zhangqianYY** [comment]
> 恩恩，代码中实际用到的只有logit_scale，temperature只是算法概念上的，实际随模型一起训练的是logit_scale

好的，感谢您的回复。

**Comment by remember00000** [comment]
请问这个图是怎么生成的呢

> ![val_loss](https://user-images.githubusercontent.com/22525110/159421617-630391b0-6e35-4ce0-8d45-c8552fe1a310.png)
> 
> 横坐标是epoch数
