### ISSUE TITLE
语言模型预训练模型问题

### ISSUE THREAD

**Issue by zhangqianYY** [MUGE-2021/image-retrieval-baseline#7]
你好，语言模型[项目](https://github.com/ymcui/Chinese-BERT-wwm)中的发布模型RoBERTa-wwm-ext-large是基于全词掩码（Whole Word Masking）方案训练得到，但image-retrieval-baseline中却没有使用相同版本的分词方法接进行finetune，我理解这会损失较大精度，是有什么考虑么？

**Comment by yangapku** [comment]
您好，RoBERTa-wwm-ext-large提到的全词掩码指的是其预训练时mask的一种特殊实现方式，并不是一种分词方式。我们使用的就是复用RoBERTa-wwm-ext-large的分词器，对于中文都采用单字分词。全词掩码指的是RoBERTa-wwm-ext-large在其纯文本预训练时，mask一个完整词语，对于组成这个词的多个单字的位置都进行mask，而不是这些单字分成一个词。
